#+TITLE: MY EMACS CONFIGURATION

이 저장소는 개인적으로 사용하고 있는 Emacs 설정 파일을 정리합니다.

* 목표
본 설정은 Emacs를 텍스트 에디터 또는 IDE로서 활용하고자 하는 (프로그래머/비프로그래머) 한국인 사용자를 목표로 하고 있습니다. 구체적으로 지향하는 목표는 아래와 같습니다.

- 한글 입력: 기본적으로 Emacs는 다국어 지원이 잘 되어 있습니다. 특히 한글의 경우, 자체적으로 훌륭한 한글 입력기를 내장하고 있는 등 다른 CJK 언어보다 더 사용이 편리한 면이 있습니다. 그럼에도, 바닐라 Emacs에서는 한글을 사용하는 데에 다소 불완전한 면이 있습니다. 본 설정은 한글 입력 및 표시 등을 잘 지원할 수 있도록 최적화하는 것을 목표로 합니다.
- 가독성: 다른 텍스트 에디터 수준 또는 그 이상으로 폰트나 레이아웃 등 가독성을 최대한 고려하여 설정합니다.
- 텍스트 입력: org-mode, markdown 등 다양한 환경과 문법에서 텍스트를 입력하거나 관리할 수 있도록 설정합니다.
- 크로스플랫폼: 윈도우 및 OSX 환경을 주된 환경으로 놓고 설정을 구현하며, 리눅스 환경에서도 사용 가능하도록 합니다.
- 자동화: [[https://github.com/jwiegley/use-package][use-package]], [[https://github.com/raxod502/straight.el][straight.el]] 등의 패키지 관리자를 사용하여 패키지 설치 및 업데이트를 자동으로 진행합니다.

* 설치법
1. 설정파일들을 다운받아 =~/.emacs.d= 디렉토리에 복사합니다. 혹은 git clone 명령어를 사용해도 됩니다(이쪽을 더 추천합니다). 윈도우즈의 경우, [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Windows-HOME.html][이 문서]]를 참고하여 폴더를 찾거나 설정합니다.
2. Emacs를 실행하여 안내를 따릅니다.

* 사용법
** 다국어 설정
기본적으로 한글(두벌식, 세벌식 390/391), 영문, 일문 입력을 바로 할 수 있도록 설정되어 있습니다.

- _C-\_: 입력기 (두벌식 - 390 - 391 - 일문) 를 전환합니다.
- _S-space: 설정한 입력기와 영문을 전환합니다.

** 파일 목록
- init.el: 처음 Emacs가 읽어들이는 파일입니다.
- freshstart.el: 맨 처음 설정을 적용한 경우, 초기화 및 필요한 패키지를 다운받기 위해 읽어들이는 파일입니다.
- config.org: 모든 설정이 모여져 있는 파일입니다. org-mode 형식으로 쓰여져 있으며, 따라서 Emacs나 Github 등에서 쉽게 읽을 수 있습니다.
  - Emacs를 실행하면 이 파일을 config.el로 변환하여 Emacs가 읽어들일 수 있도록 합니다. 만일 ==git pull== 등으로 파일을 업데이트했을 경우에는 .el 파일을 삭제해서 내용을 갱신해야 합니다.

** 패키지 목록
아래 목록은 이 설정에서 적용한 패키지 중 일부입니다. 전체 목록은 config.org 파일을 확인해 보세요.

*** 문법 확장
- markdown-mode: 마크다운을 표시 및 입력할 수 있도록 합니다.
- org: Org-mode

*** 인터페이스 확장
- writeroom-mode: 전체화면에서 수정할 수 있도록 합니다.
- powerline: vim과 유사하게 mode-line을 보기 좋게 수정해 줍니다.
- wc-mode: mode-line에 문서의 단어수를 표시합니다.

*** 기타
- magit: Git을 편리하게 관리할 수 있습니다.

** 수정사항
- 한글을 깔끔답게 표시할 수 있도록 기본 폰트를 D2Coding으로 설정하였습니다.
- Emacs에서는 패키지 관리를 위해 여러 솔루션을 제공하지만, 가장 편리하게 관리할 수 있는 use-package + straight.el을 사용하였습니다.

** TODO
- 구동시간 최적화
- 더 편리한 사용자 설정
- 별개의 프로젝트로, Emacs 한글화를 진행할 예정입니다.

** 기타
이 설정은 비정기적으로, 수시 업데이트됩니다. 개선점은 이 저장소의 issue나 이메일 (clockoon@gmail.com)을 통해 반영될 것입니다.

-- Sungbin Jeon
